---
- name: Setup editor
  become: true
  alternatives:
    name: "{{ item }}"
    path: /usr/bin/vim.nox
  with_items:
    - editor
    - vi
    - view
    - vim
    - vimdiff
    - ex
    - rvim
    - rview

- name: Setup graphical editor
  become: true
  alternatives:
    name: "{{ item }}"
    path: /usr/bin/vim.gtk3
  with_items:
    - gvim
    - gview
    - evim
    - eview
    - gvimdiff
    - rgview
    - rgvim

- name: Setup pager
  become: true
  alternatives:
    name: pager
    path: /usr/bin/most
