---
- name: Create destination directory if not present
  become: true
  file:
    path: "/usr/share/fonts/custom"
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Check if font already exists
  stat:
    path: "/usr/share/fonts/custom/{{ font_file }}"
    get_checksum: false
    get_md5: false
  register: font_info

- name: Install the font {{ font_file }}
  become: true
  get_url:
    url: "{{ font_url }}"
    dest: "/usr/share/fonts/custom/{{ font_file }}"
    owner: root
    group: root
    mode: 0644
  when: font_info.stat.exists == False
  notify: Regenerate Font Cache
