---
- name: Install fonts from packages
  become: true
  apt:
    name: "{{ item }}"
  with_items: "{{ font_packages }}"

- name: Install fonts from URL
  include: install-font-from-url.yml font_url={{ item.url }} font_file={{ item.file }}
  with_items: "{{ url_fonts }}"
