---
- name: Create the Ansible user
  become: true
  user:
    name: 'ansible'
    comment: 'Ansible Account'
    shell: '/bin/bash'
    password: '$6$zIkweK1QYw2kkCTJ$mc8tOO3s2AbvkNwpwDrx7YT/djmRDoXGY1w6YOaPFtNCPVkdDvCRrBCVa.tmqh7XCsFptfW29tr3qW77P0jal/'
    createhome: yes

- name: Add Ansible user to the default groups along with sudo and ssh
  become: true
  user:
    name: 'ansible'
    groups: 'cdrom,floppy,dip,video,plugdev,users,netdev,sudo,ssh'
    append: yes

- name: Add Ansible's authorized ED25519 SSH key
  become: true
  authorized_key:
    user: 'ansible'
    exclusive: yes
    key: "{{ lookup('file', 'keys/id_ansible_ed25519.pub') }}"
