---
ppa_repositories:
    - "ppa:libreoffice/ppa"
apt_packages:
# Audio Video Tools (Console)
    - libavcodec-extra
    - libdvd-pkg
    - gstreamer1.0-plugins-ugly
    - gstreamer1.0-plugins-bad
    - gstreamer1.0-libav
    - gstreamer1.0-fluendo-mp3
    - oxideqt-codecs-extra
    - ffmpeg
    - chromium-codecs-ffmpeg-extra
    - opus-tools
    - vorbis-tools
    - flac
    - wavpack
    - handbrake-cli
    - libav-tools
    - ffmpeg-doc
    - sox
    - libsox-fmt-all
    - speex
    - wodim
    - genisoimage
    - icedax
    - cdrdao
    - cdrkit-doc
    - growisofs
    - espeak
    - cmus
    - cmus-plugin-ffmpeg
    - mpv
    - asunder
    - kodi
# Image Manipulation Applications
    - imagemagick
    - graphicsmagick
    - libjpeg-turbo-progs
    - netpbm
    - gifsicle
    - barcode
    - icoutils
# Console Applications
    - units
    - lastpass-cli
    - lynx
    - ncdu
    - youtube-dl
    - tty-clock
    - w3m
    - unar
    - vrms
    - p7zip-full
    - cabextract
    - lzma
    - poppler-utils
# Media and file sharing
    - samba
    - samba-dev
    - minidlna
# Audio Video Tools (X11)
    - vlc
    - vlc-plugin-samba
    - handbrake
# X11 Applications
    - usb-creator-gtk
    - freerdp-x11
    - gnome-font-viewer
    - font-manager
    - synaptic
    - vinagre
    - vino
    - galculator
    - evince
    - pidgin
    - pidgin-data
    - bleachbit
    - cheese
    - shotwell
    - clementine
    - get-flash-videos
    - ntop
    - gimp
    - gimp-help-en
    - gimp-plugin-registry
    - gimp-ufraw
    - inkscape
    - dia
    - krita
    - scribus
    - scribus-doc
    - scribus-template
    - libreoffice
    - hunspell-en-us
    - hyphen-en-us
    - mythes-en-us
    - libreoffice-dev
    - libreoffice-dev-doc
    - libreoffice-dmaths
    - libreoffice-gtk3
    - libreoffice-help-en-us
    - libreoffice-lightproof-en
    - libreoffice-report-builder
    - libreoffice-script-provider-js
    - libreoffice-script-provider-python
    - libreoffice-templates
    - unoconv
    - openclipart-libreoffice
    - openclipart2-libreoffice
    - blender
    - darktable
    - mypaint
    - audacity
    - musescore
    - qbittorrent
    - deluge
    - deluge-console
    - deluge-web
    - caffeine
    - convertall
## Dev packages
    - build-essential
    - dkms
    - apt-transport-https
    - ca-certificates
    - software-properties-common
    - virt-what
    - patchutils
    - module-assistant
    - binutils
    - cmake
    - manpages-dev
    - strace
    - ltrace
    - fakeroot
    - autoconf
    - autoconf-archive
    - automake
    - bison
    - flex
    - gdb
    - libtool
    - gnu-standards
    - gfortran
    - gettext
    - cscope
    - highlight
    - source-highlight
    - lintian
    - sloccount
    - cloc
    - diffutils
    - indent
    - awscli
    - unixodbc
    - qtbase5-dev
    - qtbase5-doc-html
    - qtbase5-examples
    - libqt5x11extras5-dev
    - libqt5svg5-dev
    - libmuparser-dev
    - wdiff
    - snapcraft
    - lua-check
    - phantomjs
    - licenseutils
# X11 Dev Applications
    - git-cola
    - zeal

#pip2_packages:
#    - geeknote

deb_packages:
    - "https://github.com/jarun/googler/releases/download/v2.6/googler_2.6-1_all.deb"
