---
- name: Install python
  become: true
  apt:
    name: "{{ item }}"
  with_items:
    - python-dev
    - python3-dev
    - python-examples
    - python3-examples
    - libkrb5-dev
    - libssl-dev
    - libffi-dev
    - python-pip
    - python3-pip
    - virtualenv
    - virtualenvwrapper
