---
- name: Update the package cache
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Ensure aptitude is installed
  become: true
  apt:
    name: "{{ item }}"
  with_items:
    - aptitude

- name: Upgrade the packages
  become: true
  apt:
    upgrade: "{{ apt_upgrade_level | default(safe) }}"
