---
- name: Add user primary groups
  become: true
  group:
    name: '{{ item.name }}'
    state: present
  with_items: '{{ users }}'

- name: Create users
  become: true
  user:
    name: '{{ item.name }}'
    comment: '{{ item.comment }}'
    group: '{{ item.name }}'
    shell: '{{ item.shell }}'
    password: '{{ item.password }}'
    createhome: yes
  with_items: '{{ users }}'

- name: Add users to the default groups
  become: true
  user:
    name: '{{ item[0].name }}'
    groups: '{{ item[1] }}'
    append: yes
  with_nested:
    - '{{ users }}'
    - '{{ default_groups }}'

- name: Add users to the sudo group
  become: true
  user:
    name: '{{ item }}'
    groups: 'sudo'
    append: yes
  with_items: '{{ sudo_users }}'

- name: Allow svcacct user to run sudo without a password
  become: true
  template:
    src: etc-sudoers.d--svcacct.j2
    dest: /etc/sudoers.d/svcacct
    owner: root
    group: root
    mode: 0440
    backup: no

- name: Add users to the ssh group
  become: true
  user:
    name: '{{item.name}}'
    groups: 'ssh'
    append: yes
  with_items: '{{ ssh_users }}'

- name: Add users authorized RSA SSH key
  become: true
  authorized_key:
    user: '{{ item.name }}'
    key: "{{ lookup('file', item.public_rsa_key) }}"
  with_items: '{{ ssh_users }}'

- name: Add users authorized ED25519 SSH key
  become: true
  authorized_key:
    user: '{{ item.name }}'
    key: "{{ lookup('file', item.public_ed25519_key) }}"
  with_items: '{{ ssh_users }}'
