---
- name: Install KDE Backports PPA
  become: true
  apt_repository:
    repo: "{{ item }}"
    mode: 0644
    update_cache: yes
  with_items:
    - "ppa:kubuntu-ppa/backports"

- name: Install KDE desktop
  become: true
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - kubuntu-full
    - kleopatra
    - dolphin-plugins
    - kde-thumbnailer-openoffice
    - kde-wallpapers
    - kdeartwork-wallpapers
