---
- name: Install python packages
  become: true
  apt:
    name: "{{ item }}"
  with_items:
    - python-dev
    - python3-dev
    - libkrb5-dev
    - libssl-dev
    - libffi-dev

- name: Checking for pip3
  stat:
    path:  /usr/local/bin/pip3
    get_checksum: false
    get_md5: false
  register: pip3_status

- name: Checking for pip2
  stat:
    path:  /usr/local/bin/pip2
    get_checksum: false
    get_md5: false
  register: pip2_status

- name: Download pip install script
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /tmp/get-pip.py
  when: (pip3_status.stat.exists == False) or (pip2_status.stat.exists == False)

- name: Install pip3
  become: true
  shell: python3 /tmp/get-pip.py
  args:
    creates: /usr/local/bin/pip3
  when: pip3_status.stat.exists == False

- name: Install pip2
  become: true
  shell: python2 /tmp/get-pip.py
  args:
    creates: /usr/local/bin/pip2
  when: pip2_status.stat.exists == False
